<a href="https://colab.research.google.com/github/johnjar99/curso_python-/blob/main/sesion5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
divmod(13,5)

(2, 3)

In [ ]:
entero,residuo=divmod(13,5)
print(entero,residuo)

2 3


In [ ]:
entero+9

11

In [ ]:
0 or 0

0

In [ ]:
[] and 15

[]

In [ ]:
45 and 15

15

In [ ]:
not 1

False

In [ ]:
5>4 and 3<5 or 4>1

True

In [ ]:
a=12 #base de datos 
b=a #copia de respaldo 
c=12

In [ ]:
print(id(a),id(b),id(c),a==c)

11256416 11256416 11256416 True


In [ ]:
b=17

In [ ]:
a

12

In [ ]:
a is b
a is c

True

In [ ]:
nombre="john"

In [ ]:
nombre[0]

'j'

In [ ]:
print( nombre[0], nombre[-1])

j n


STRING (CADENA) INMUTABLES


In [ ]:
nuevo_nombre=nombre.capitalize()

In [ ]:
nuevo_nombre

'John'

In [ ]:
dir(nombre)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',


In [ ]:
nombre.zfill?

In [ ]:
nombre.zfill(1)

'john'

In [ ]:
cadena="abcdefg"
cadena.index("a")

0

In [ ]:
cadena.find("h")

-1

In [ ]:
lista=list(cadena)
lista[0]="J"
lista

['J', 'b', 'c', 'd', 'e', 'f', 'g']

In [ ]:
cadena1="".join(lista)
cadena1

'Jbcdefg'

CONTENEDORES

In [ ]:
l=[1,2,3,4,5,6]
l

[1, 2, 3, 4, 5, 6]

In [ ]:
l.reverse()


[6, 5, 4, 3, 2, 1]

In [ ]:
l.pop(5)
l

[1, 2, 3, 4, 5]

In [ ]:
l.extend(l)
l

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [ ]:
l.append([77])
l

[1, 2, 3, 4, 5, 6, 77, [77]]

In [ ]:
l[-1]

[77]

In [ ]:
l[-1][0]

77

In [ ]:
l[-1][0]+2

79

TUPLAS


In [ ]:
j=(2,3)

In [ ]:
dir(j)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'count',
 'index']

In [ ]:
y=(12,3,3,2,4,4,"hola",[2,3,3,],(2.3),(2,3))

In [ ]:
y.count("hola")

1

In [ ]:
y.index("hola")

6

index con elementos repetidos 

In [ ]:
y.index("hola",0,11)

6

In [ ]:
Y=list(y)
Y

[12, 3, 3, 2, 4, 4, 'hola', [2, 3, 3], 2.3, (2, 3)]

sort organiza listas con criterio comun

In [ ]:
lista1=[1,2,3]
lista2=lista1.copy()

In [ ]:
print(id(lista1),id(lista2))

139763784078272 139763783486432


In [ ]:
lista3=[1,2,3,[4,5],(6,7)]
import copy
lista4=copy.deepcopy(lista3)
print(id(lista3),id(lista4))

139763783284928 139763783088720


CONDICIONAL

IF

In [ ]:
edad=12
if edad >=18:
  print("Es mayor de edad")
else:
  print("Es menor de edad")

Es menor de edad


In [ ]:
calificacion=[]
if calificacion: #verdadero
  print("el estudiante existe")
else:
  print("no existe")  

no existe


In [ ]:
calificacion=5
if calificacion >=0 and calificacion <1:
  print("D")
elif  calificacion >=1 and calificacion <2:
  print("I")
elif calificacion >=2 and calificacion <3:  
  print("A")
elif calificacion >=3 and calificacion <4:  
  print("S")
elif calificacion >=4 and calificacion <=5: 
  print("E")
else:
  print("calificacion incorrecta")   


E


FOR

In [ ]:
lista4

[1, 2, 3, [4, 5], (6, 7)]

In [ ]:
for i in lista4:
  print(i)

1
2
3
[4, 5]
(6, 7)


In [ ]:
list(enumerate(lista4))

[(0, 1), (1, 2), (2, 3), (3, [4, 5]), (4, (6, 7))]

In [ ]:
for i in list(enumerate(lista4)):
  print(i)

(0, 1)
(1, 2)
(2, 3)
(3, [4, 5])
(4, (6, 7))


In [ ]:
for i in list(enumerate(lista4)):
  indice,elemento=i
  print(indice)

0
1
2
3
4


In [ ]:
for i in list(enumerate(lista4)):
  indice,elemento=i
  print(indice)
  if indice==3:
    break

0
1
2
3


In [ ]:
for i in list(enumerate(lista4)):
  indice,elemento=i
  print(indice)
else:
  print("operacion termina")  

0
1
2
3
4
operacion termina


WHILE

RANGE

In [ ]:
for i in range(1,9,2):
  print(i)

1
3
5
7


In [ ]:
range(2,9,1)
list(range(2,9,1))

[2, 3, 4, 5, 6, 7, 8]

EJERCIO 1

In [ ]:
a=int(input("Ingrese primer entero"))
b=int(input("Ingrese segundo entero"))
if a==b:
  print("Si, los numeros son iguales")
else:
  print("No, los numeros son diferentes")  

Ingrese primer entero14
Ingrese segundo entero50
No, los numeros son diferentes


EJERCICIO 2

In [ ]:
a=int(input("Ingrese numero"))
if a%2==0:
  print("Par")
else:
  print("Impar")  

Ingrese numero7
Impar


EJERCICIO 3

In [ ]:
a=int(input("Ingrese numero"))
if a<0:
  print("El numero es negativo")
else:
  print("El numero es positivo")

Ingrese numero-8
El numero es negativo


EJERCICIO 4

In [ ]:
L=[1,33,52,65,123,32]
suma=0
for i in L:
  suma=suma+i
print(suma)  

306


EJERCICIOS

1. Programa que encuentre todos los numeros que son divisiblen entre 7 pero no son multiplos de 5 ente 2000 y 3200 ambos numeros incluidos 

In [ ]:
linf=2000
lsup=3200
k=0
for i in range(linf,lsup+1,1):
  if i%7==0 and i%5:
    k+=1
print("el total de números encontrados es: -> ",k)

el total de números encontrados es: ->  138


2.Escriba un programa que calcule si N es un numero primo 

In [ ]:
N=1
f=0 #flag-> bandera, señal
for i in range(2,N):# No necesito N exacto, ni el 1
  if N%i==0:
    print("El número no es primo")
    f=1
    break
if f==0:# ==1 (verdadero!)
  print('El número es primo')

El número es primo


3.Escriba un programa que calcule la suma de tos los elementos de una lista

In [ ]:
lista=[1,2,3,4,5,6,7,8,9]
suma_lista=sum(lista)
suma_lista

45

4. Escriba un programa que cuente cuantos numeros son multiplos 2 de una lista 

In [ ]:
lista=[5,4,8,7,6,9,5,23]
k=0
for i in lista:
  if i%2==0:
    k=k+1
print(k)    

3


5. Escriba un programa qu einvierta una cadena de texto

In [ ]:
cadena= "John"
list_cadena=list(cadena)
list_cadena
list_cadena.reverse()
' '.join([str(elem) for elem in list_cadena])

'n h o J'

6. Escriba un programa que cuente cuantas veces aparece la letra "a" en una palabra

In [ ]:
a="caracteristica"
a.count("a")

3

7.Escriba un programa que decida si dos contenedores son iguales 

In [ ]:
contenedor1= [4,5,5,(7,8),"hola"]
contenedor2= [4,5,8 ,7,"hola"]
if contenedor1==contenedor2:
  print("los contenedores son iguales")
else:
  print("los contenedores son diferentes")

los contenedores son diferentes


8. Escriba un programa que calcule el factorial de un numero 

In [ ]:
a=int(input())
fact=1
if a==0:
  fact=1
else:
  for i in range(2,a+1):
    fact=fact*i
print(fact)


1
1


9. Escriba un programa que dado dos numeros eleve el primero al segundo

In [2]:
def a_potencia_b(a,b):
  return a**b

In [3]:
a_potencia_b(2,3)

8

10. Escriba un programa que decida si un elemento se encuentra en un contenedor 

In [ ]:
a=int(input("elemento en el contenedor:"))
contenedor=int(input("elementos del contenedor:"))
contenedor_final=[]
for i in range(contenedor):
  contenedor_final.append(int(input()))

if a in contenedor_final:
  print(a, "esta en el contenedor ")
else:
  print(a, "no esta en el contenedor")  

elemento en el contenedor:4
elementos del contenedor:2
1
2
4 no esta en el contenedor


DESEMPAQUETAR LISTAS O TUPLAS

In [ ]:
a=(1,2,3,5,4,7)
b=[1,2,5,4,7,8]

In [ ]:
a,s,d,f,g,e=a

In [ ]:
a+12

13

CONJUTOS:SETS

In [ ]:
d={1,2,3}
type(d)

set

In [ ]:
d={}
type(d)

dict

In [ ]:

nombres={"John","Andres","Cristiano","Sergio"}

In [ ]:
print(nombres)

{'John', 'Cristiano', 'Andres', 'Sergio'}


In [ ]:
for i in nombres:
  print(i)

John
Cristiano
Andres
Sergio


In [ ]:
sorted(nombres)

['Andres', 'Cristiano', 'John', 'Sergio']

In [ ]:
METODO .add()

In [ ]:

nombres.add("Sil")
nombres

{'Andres', 'Cristiano', 'John', 'Sergio', 'Sil'}

METODO .remove()

In [ ]:

nombres.remove("John")
nombres

{'Andres', 'Cristiano', 'Sergio', 'Sil'}

.discard() no devuleve error si no encuntra el elemento x a remover 

METODO .pop

In [ ]:
nombres.pop()
nombres

{'Andres', 'Sergio'}

METODO .copy() deepcopy SAME

In [ ]:
nuevo_nombres=nombres.copy()
nuevo_nombres

{'Andres', 'Sergio'}

METODO .clear()

In [ ]:
nombres.clear()
nombres

set()

OPERACIONES Y SUS OPERADORES EN CONJUNTOS 


OPERADOR in


In [ ]:
"Andres" in nombres

False

DIFERENCIA DE CONFUNJOS 

In [ ]:
nuevo_nombres-nombres
nuevo_nombres.difference(nombres)
nuevo_nombres.difference_update(nombres)

set()

INTERSECCION

In [ ]:
nuevo_nombres & nombres
nuevo_nombres.intersection(nombres)
nuevo_nombres.intersection_update(nombres)

UNION

In [ ]:
nuevo_nombres | nombres
nuevo_nombres.union(nombres)

DIFERENCIA SIMETRICA A|B-A & B

In [ ]:
nuevo_nombres.symmetric_difference(nombres)
nuevo_nombres.symmetric_difference_update(nombres)

ACTUALIZAR CONJUNTO agregar los elementoas que  no existen 

In [ ]:
nuevo_nombres.update(["John"])
nuevo_nombres

{'Andres', 'Cristiano', 'John', 'Sergio'}

OPERADORES BOLEANOS


DISYUNTOS 

In [ ]:
nuevo_nombres.isdisjoint(nombres)


SUBCONJUNTO O SUPERCONJUNTO

In [ ]:
nuevo_nombres.issubset(nombres)
nuevo_nombres.issuperset(nombres)

DICCIONARIOS

In [ ]:
edades={"john":22,"andres":23,"sil":23}
edades

{'andres': 23, 'john': 22, 'sil': 23}

USO DE LA CLAVE

In [ ]:
edades["john"]

22

In [ ]:
18 in edades

False

In [ ]:
"john" in edades

True

In [ ]:
edades["john"]+1

23

.get()

In [ ]:
edades.get("juanis",0)

0

In [ ]:
edades.get("john",0)

22

.setdefault()

In [ ]:
edades

{'andres': 23, 'john': 22, 'sil': 23}

In [ ]:
edades.setdefault("juan",24)
edades

{'andres': 23, 'john': 22, 'juan': 24, 'sil': 23}

.items() .keys() .values()a

In [ ]:
edades.items()

dict_items([('john', 22), ('andres', 23), ('sil', 23), ('juan', 24)])

In [ ]:
edades.keys()

dict_keys(['john', 'andres', 'sil', 'juan'])

In [ ]:
edades.values()

dict_values([22, 23, 23, 24])

In [ ]:
for nombre,edad in edades.items():
  print(nombre,edad)

john 22
andres 23
sil 23
juan 24


.pop() .popitem()

In [ ]:
edades.pop("john")

22

In [ ]:
edades.popitem()

('juan', 24)

EJERCICIOS

In [ ]:
precios={"bananos":300,"manzanas":1000,"mangos":800,"piñas":2200}

precio de 10 bananos mas 5 manzanas mas 3 mangos 


In [ ]:
precios["bananos"]*10+precios["mangos"]*3+precios["manzanas"]*5

10400

dada frase, almacenar en u diccionario las letras y las veces que aparece la letra en la frase 

In [ ]:
frase="hola, damas y caballeros. Bienvenidos al curso de python"

In [ ]:
set(frase)

{' ',
 ',',
 '.',
 'B',
 'a',
 'b',
 'c',
 'd',
 'e',
 'h',
 'i',
 'l',
 'm',
 'n',
 'o',
 'p',
 'r',
 's',
 't',
 'u',
 'v',
 'y'}

In [ ]:
respuesta={}
for i in set(frase):
  respuesta[i]=frase.count(i)
respuesta

{' ': 8,
 ',': 1,
 '.': 1,
 'B': 1,
 'a': 6,
 'b': 1,
 'c': 2,
 'd': 3,
 'e': 4,
 'h': 2,
 'i': 2,
 'l': 4,
 'm': 1,
 'n': 3,
 'o': 5,
 'p': 1,
 'r': 2,
 's': 4,
 't': 1,
 'u': 1,
 'v': 1,
 'y': 2}

EJERCICIOS

1.

In [ ]:
grades = {'juan':(5.0, 5.0,4.9,4.0), 'david': (1.0,3.0,4.5,5.0), 'jose':(2.0,1.0,3.5,5.0), 'daniela':(0.0,5.0,5.0,5.0) }
dic= dict()
for nombre, notas in grades.items():
  dic[nombre]=round(sum(notas)/len(grades.items()),2)
print(dic) 

2.

In [ ]:
grades = {'juan':[5.0, 5.0,4.9,4.0], 'david': [1.0,3.0,4.5,5.0], 'jose':[2.0,1.0,3.5,5.0], 'daniela':[0.0,5.0,5.0,5.0] }
grades
dic= dict()
for nombre, notas in grades.items():
  notas.sort(reverse=True)
  dic[nombre]=round(sum(notas[0:3])/len(notas[0:3]),2)
print(dic)

{'juan': 4.97, 'david': 4.17, 'jose': 3.5, 'daniela': 5.0}


3.

In [ ]:
d={}
for i in range(0,5+1):
  n=input("nombre")
  e=int(input("edad"))
  d[n]=e
d

nombrejohn
edad23
nombresil
edad21
nombreandres
edad25
nombrecarlos
edad7
nombresamu
edad5
nombreisa
edad9


{'andres': 25, 'carlos': 7, 'isa': 9, 'john': 23, 'samu': 5, 'sil': 21}

Programa que una dos diccionarios 

In [ ]:
a={"dd":3,"ee":4}
b={"aa":5,"ff":6}
a.update(b)
a

{'aa': 5, 'dd': 3, 'ee': 4, 'ff': 6}

Programa para saber si una key(clave) esta en un diccionario 

In [ ]:
clave="dd"
clave in a

True

Programa que genere un diccionaro cuya clave sea un numero y el valor sea su cuadrado 

In [ ]:
n=12
diccionario={}
for i in range(1,n+1):
  diccionario[i]=i**2
diccionario

{1: 1,
 2: 4,
 3: 9,
 4: 16,
 5: 25,
 6: 36,
 7: 49,
 8: 64,
 9: 81,
 10: 100,
 11: 121,
 12: 144}

Programa que mape dos listas en un diccionario

In [ ]:
l1=[1,2,3,4,5]
l2=[2,8,9,7,4]
diccionario["l1"]=l1
diccionario["l1"]=l2

In [ ]:
diccionario

{1: 1,
 10: 100,
 11: 121,
 12: 144,
 2: 4,
 3: 9,
 4: 16,
 5: 25,
 6: 36,
 7: 49,
 8: 64,
 9: 81,
 'l1': [2, 8, 9, 7, 4]}

Programa que obtenga el maximo value de un diccionario y su respectivo key 

In [ ]:
a={"aa":3,"bb":4,"cc":5}
x=max(a.values())
for i,v in a.items():
  if v==x:
    print(i)
    break

cc


FUNCIONES

In [ ]:
def imprimir_mesa():
  print("hola mundo ")

In [ ]:
imprimir_mesa()

hola mundo 


argumentos

In [ ]:
def suma(a,b):
  return a+b

In [ ]:
suma(1,2)

3

In [ ]:
def numero_par(x):
  return x%2==0

In [ ]:
numero_par(5)

False

In [ ]:
def cuadrado_raiz(x):
  return x**2,x**0.5

In [ ]:
cuadrado_raiz(5)

(25, 2.23606797749979)

DEFINIR ARGUMENTOS DE UNA FUNCION Y ARGUMENTOs POR DEFECTO

In [ ]:
def potencia(numero,exponente=2):
  return numero**exponente

In [ ]:
potencia(4)

16

In [ ]:
potencia(exponente=2,numero=3)

9

FUNCIONES CON CUALQUEIR NUMERO DE ARUGUMENTOS 

In [ ]:
def sumar1(*sumandos):
  suma1=0
  for i in sumandos:
    suma1=suma1+i
  return suma1

In [ ]:
sumar1(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20)

210

RESTRICCION A LOS ARGUMENTOS se obliga a escribir el nmbre

In [ ]:
def potencia1(*,numero,exponente):
  return numero**exponente

In [ ]:
potencia1(numero=1,exponente=2)

1

PARAMETROS ADICCIONALES ingresa los argumentos en un diccionario



In [ ]:
def colores(**kwargs):
  print(kwargs)

In [ ]:
colores(a=5,rojo="john")

{'a': 5, 'rojo': 'john'}


In [ ]:
import math
def area_cuadrado(a):
  return a*a
def area_trian(b,a):
  return b*a/2
def area_circ(r):
  return math.pi*r**2

In [ ]:
def area_figura(nombre,**parametros_caract):
  if nombre=="cuadrado":
    return area_cuadrado(**parametros_caract)
  elif nombre=="triangulo":
    return area_trian(**parametros_caract)
  elif nombre=="circulo":
    return area_circ(**parametros_caract)

In [ ]:
area_figura("cuadrado",a=5)

25

In [ ]:
area_figura("circulo",r=5)

78.53981633974483

In [ ]:
area_figura("triangulo",b=5,a=7)

17.5

In [ ]:
def area_figura(nombre,**parametros_caract):
  if nombre=="cuadrado":
    return print(parametros_caract)
  elif nombre=="triangulo":
    return print(parametros_caract)
  elif nombre=="circulo":
    return print(parametros_caract)

In [ ]:
area_figura("circulo",r=2)

{'r': 2}


In [ ]:
area_figura("triangulo",a=2,b=7)

{'a': 2, 'b': 7}


In [ ]:
area_figura("cuadrado",a=5)

{'a': 5}


FUNCIONES QUE RECIBEN FUNCIONES COMO ARGUMENTOS: MAPPER mapper in built es map()

In [ ]:
def potencia_lista(funcion,lista):
  salida=[]
  for i in lista:
    salida.append(funcion(i))
  return salida

In [ ]:
a=[1,2,3,4,5]
potencia_lista(raiz_cuadrada,a)

[1.0, 1.4142135623730951, 1.7320508075688772, 2.0, 2.23606797749979]

In [ ]:
list(map(math.sqrt,a))

[1.0, 1.4142135623730951, 1.7320508075688772, 2.0, 2.23606797749979]

FUNCIOON LAMBDA anonima, es una linea de textp, sin palabra clave(def)

In [ ]:
raiz_cuadrada=lambda x:x**0.5

In [ ]:
list(map(raiz_cuadrada,a))

[1.0, 1.4142135623730951, 1.7320508075688772, 2.0, 2.23606797749979]

In [ ]:
potencia_lambda= lambda *,n,expo:n**expo
potencia_lambda(expo=2,n=2)

4

In [ ]:
imprimir_num= lambda *num:print(num)
print("es una tupla!")
imprimir_num(2,3,4,5,8)

es una tupla!
(2, 3, 4, 5, 8)


In [ ]:
imprimir_num= lambda **num:print(num)
print("es un diccionario!")
imprimir_num(a=3,b=4,c=5)

es un diccionario!
{'a': 3, 'b': 4, 'c': 5}


FUNCION filter()

In [ ]:
filter()
#recibe una funcion y un iterable
#devuleve los items del iterable en que la funcion es true

In [ ]:
list(filter(lambda x:x%2==0,range(11)))

[0, 2, 4, 6, 8, 10]

In [ ]:
a
list(filter(lambda x:x%2==0,a))

[2, 4]

CREAR E IMPORTAR UN MODULO DE FUNCIONES

In [ ]:
import copy
copy.deepcopy
import math
math.pi 
#importar 

In [ ]:
import funciones
funciones.mm(5)
funciones.GG(5)

10

EJERCICIOS

UNA FUNCION QUE CALCULE EL PROMEDIO DE CUALQUIER N NUMEROS

In [ ]:
def promedio_N(*numeros):
  return sum(numeros)/len(numeros)

In [ ]:
promedio_N(1,2,3,4,5,6,7,8,9)

5.0

In [ ]:
promedio_N= lambda *numeros:sum(numeros)/len(numeros)
promedio_N(1,2,3,4,5,6,7,8,9)

5.0

FUNCION QUE VERIFICAR QUE UN STR ES O NO UN PALINDROMO

In [ ]:
l="taco cat"
l1=list(l.replace(" ","").lower())
g=list(reversed(l.replace(" ","").lower()))
print(list(l),l1,g)
if l1==g:
  print("es un palindromo")
else:
  print("no es un palindromo")
#l[-1:len(l)-1:-1] #lista[inicio:fin-1:paso]

['t', 'a', 'c', 'o', ' ', 'c', 'a', 't'] ['t', 'a', 'c', 'o', 'c', 'a', 't'] ['t', 'a', 'c', 'o', 'c', 'a', 't']
es un palindromo


In [ ]:
def palindromo(cadena):
  n_cadena=cadena.replace(" ","").lower()
  cadena2=""
  for i in range(len(n_cadena)):
    cadena2=cadena2+n_cadena[-i-1]
  return cadena2==n_cadena

In [ ]:
palindromo("taco cat")

True

In [ ]:
cadena.lower?

EJERCICIOS

Escriba una funcion que encuentre el minumo de tres numeros 

In [4]:
def minimo(a,b,c):
  return min(a,b,c)

In [6]:
minimo(5,5,5)

5

Escriba una funcion que calcule el factorial de un numero (entero positivo)

In [9]:
def Factorial(n):
  f=1
  for i in range(2,n+1):
    f=f*i
  return f  

In [11]:
Factorial(4)

24

Escriba una fucion que identifique si un numero se encuentra o no en un rango dado 

In [2]:
def numero_rango(n,inf,sup):
  if n>=inf and n<=sup:
    return "esta en el rango"
  else:
    return "no esta en el rango"  

In [3]:
numero_rango(6,55,88)

'no esta en el rango'

Funcion que cuente cuantas Mayus y minus hay en un STR

In [10]:
intro_nombre="Hola mundo mi nombre es John"
def mayus_minus(cadena):
  mayus=0
  minus=0
  for i in cadena:
    if i.isalpha():
      if i.islower():
        minus=minus+1
      else:
        mayus=mayus+1
  return mayus,minus

In [11]:
mayus_minus(intro_nombre)

(2, 21)

funcion que reciba una lista y devuleva una lista con los elementos unicos de la lista

In [12]:
def unicos(lista):
  return list(set(lista))

In [13]:
unicos(intro_nombre)

['h',
 'n',
 's',
 'J',
 'a',
 'd',
 ' ',
 'm',
 'o',
 'u',
 'b',
 'e',
 'r',
 'i',
 'l',
 'H']

NUMPY: Numeric Python 

In [14]:
import numpy 
#en el local pip instal numpy 

In [15]:
numpy.__version__

'1.21.6'

In [ ]:
import copy as cp #importar paquetes con un alias
cp.deepcopy
import matplotlib.pyplot as plt
plt.
import numpy as np
np.

ARREGLO DE NUMPY VS PYTHON

In [17]:
a=(2,5)
b=(3,5)

In [16]:
import numpy

In [25]:
aN=numpy.array(a)
bN=numpy.array(b)

In [28]:
print(aN,bN)
aN+bN

[2 5] [3 5]


array([ 5, 10])

EN NUMPY todos los elementos se convierten al tip mas general de dapts: str, float, int, bool

In [19]:
c=numpy.array(["2",3,4])

In [20]:
c

array(['2', '3', '4'], dtype='<U21')

In [23]:
d=numpy.array([True,2,3,5])
d

array([1, 2, 3, 5])

In [30]:
d=numpy.array([True,2,3,5],dtype=int)
d

array([1, 2, 3, 5])

INDEXACION DE NUMPY array. 

In [34]:
e=numpy.random.uniform(0,100,(4,4))
e

array([[68.14609193, 70.73953848, 51.52670523, 32.741656  ],
       [93.84803117, 58.47565314, 41.3039966 , 81.64699026],
       [ 9.87840806, 23.48771789, 98.49196011, 86.09555037],
       [51.78594322, 80.22490506, 10.59739365, 41.98311495]])

In [38]:
e[0,3]
e[2][2]

98.49196011385366

SLICING como en listas y tuplas (NUNCA se toma el ultimo)

In [51]:
e[0:2,0:4] #Elementos del eje 0, Elemetos del eje1 

array([[68.14609193, 70.73953848, 51.52670523, 32.741656  ],
       [93.84803117, 58.47565314, 41.3039966 , 81.64699026]])

In [53]:
f=numpy.random.uniform(0,100,(2,2,3))
f

array([[[85.16382486, 19.27679069, 68.16732914],
        [73.93706207,  5.51473394, 96.62932823]],

       [[17.76449797, 65.32536359, 62.86879627],
        [84.55476852, 17.42391779, 88.75090809]]])

In [61]:
f[1,1,1]

17.4239177906908

In [63]:
f[0:3,0:3,0:4]

array([[[85.16382486, 19.27679069, 68.16732914],
        [73.93706207,  5.51473394, 96.62932823]],

       [[17.76449797, 65.32536359, 62.86879627],
        [84.55476852, 17.42391779, 88.75090809]]])

MUTABILIDA DE LOS ARREGLOS NUMPY (son mutables)



In [65]:
f[1,1,1]=17
f

array([[[85.16382486, 19.27679069, 68.16732914],
        [73.93706207,  5.51473394, 96.62932823]],

       [[17.76449797, 65.32536359, 62.86879627],
        [84.55476852, 17.        , 88.75090809]]])

COPY Y DEEPCOPY (los slices de arreglo tiene ubicacion propia en memoria)

CONVERTIR LISTAS EN MATRICES (solo para listas de listas simetricas)

In [67]:
g=numpy.array([[1,2,3],[4,5,6]])
g

array([[1, 2, 3],
       [4, 5, 6]])

METODO .shape()

In [70]:
g.shape

(2, 3)

In [71]:
f.shape

(2, 2, 3)

In [73]:
print(f)

[[[85.16382486 19.27679069 68.16732914]
  [73.93706207  5.51473394 96.62932823]]

 [[17.76449797 65.32536359 62.86879627]
  [84.55476852 17.         88.75090809]]]


METODO len()

In [74]:
len(f) #entrga la dimension del eje 0

2

In [80]:
ff=f.sum(axis=0)
print(ff,ff.shape)

[[102.92832283  84.60215428 131.03612541]
 [158.49183059  22.51473394 185.38023633]] (2, 3)


In [86]:
f[0,0]+f[1,0]

array([102.92832283,  84.60215428, 131.03612541])

In [79]:
fff=ff.sum(axis=0)
print(fff,fff.shape)

[261.42015342 107.11688822 316.41636174] (3,)


In [82]:
ffff=fff.sum(axis=0)
print(ffff,ffff.shape)

684.9534033813085 ()


LINSPACE(INICIO,FIN,NUMERO DE DATOS)

In [91]:
h=numpy.linspace(0,10,10)
print(h,h[-1],h[0])


[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ] 10.0 0.0


METODO .reshape(dim1,dim2,.....)

In [105]:
print(f)
print(f.shape)
print(f.reshape(2,6))

[[[85.16382486 19.27679069 68.16732914]
  [73.93706207  5.51473394 96.62932823]]

 [[17.76449797 65.32536359 62.86879627]
  [84.55476852 17.         88.75090809]]]
(2, 2, 3)
[[85.16382486 19.27679069 68.16732914 73.93706207  5.51473394 96.62932823]
 [17.76449797 65.32536359 62.86879627 84.55476852 17.         88.75090809]]


METODO ones()-zeros()-identity()



In [111]:
numpy.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [112]:
numpy.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [113]:
numpy.identity(2)

array([[1., 0.],
       [0., 1.]])

MATRIZ TRANSPUESTA

In [117]:
t=f.transpose() #inversion de los ejes 
print(f)
print(t,t.shape)

[[[85.16382486 19.27679069 68.16732914]
  [73.93706207  5.51473394 96.62932823]]

 [[17.76449797 65.32536359 62.86879627]
  [84.55476852 17.         88.75090809]]]
[[[85.16382486 17.76449797]
  [73.93706207 84.55476852]]

 [[19.27679069 65.32536359]
  [ 5.51473394 17.        ]]

 [[68.16732914 62.86879627]
  [96.62932823 88.75090809]]] (3, 2, 2)


In [125]:
tt=f.transpose(2,2,3)

ValueError: ignored

AJUSTE POLINOMIAL

In [127]:
x=numpy.arange(0,10) #(star,stop,step) 
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
y=x**2
y

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [130]:
numpy.polyfit(x,y,2) #coeficientes (estimadores) del ajuste polonomial 

array([ 1.00000000e+00, -5.76177365e-15,  1.53728415e-14])

EJERCICIOS:
-Sea x un arreglo de numeros aleatorios, dist unif, entre -1 y 1. Comprueben que la media es cero.
-Resolver el sistema de acuaciones.
-Sumar todos los numeros de un arreglo numpy devisibles por 7 pero no divisibles por 5.

INDEXACION BOOLEANA: FILTROS-MASCARAS